### ISSUE TITLE
factory isn't called for context values?

### ISSUE THREAD

**Issue by scamden** [maurizzzio/math-codegen#4]
seems like it might be a nice feature and a lot more consistent if the factory method were called on values pulled from the context on eval. my use case is a decimal.js adapter for math-codegen, all the methods assume decimal.js objects coming in since that's what the factory returns but then I have to create decimal objects when I supply the context object as well. would be nice to just call the factory for those as well. 

the adapter (WIP) is here if you're curious: https://github.com/creditiq/decimal-math-ops/blob/master/src/index.ts

thanks for this lib! great stuff!

**Comment by scamden** [comment]
@mauriciopoppe hello?

**Comment by mauriciopoppe** [comment]
hi, sorry for not answering to this thread before, I've created a PR that implements this feature with a new flag, let's continue the conversation in the PR and close this issue once it's merged

**Comment by scamden** [comment]
oh ok awesome! thanks for the info! great lib!
